# da onde eu tirei essa config
#https://kind.sigs.k8s.io/docs/user/configuration/#clusterwide-options


kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker